"""UI class, responsible for printing nicely formatted output to STDOUT."""
import curses
import logging
import sys
from typing import Callable

from algobattle.observer import Observer
from algobattle.match import Match
from algobattle import __version__ as version

logger = logging.getLogger('algobattle.ui')


class Ui(Observer):
    """The UI Class declares methods to output information to STDOUT."""

    def check_for_terminal(function: Callable) -> Callable:
        """Ensure that we are attached to a terminal."""
        def wrapper(self, *args, **kwargs):
            if not sys.stdout.isatty():
                logger.error('Not attached to a terminal.')
                return None
            else:
                return function(self, *args, **kwargs)
        return wrapper

    @check_for_terminal
    def __init__(self) -> None:
        if sys.stdout.isatty():
            self.stdscr = curses.initscr()
            curses.cbreak()
            curses.noecho()
            self.stdscr.keypad(1)

    @check_for_terminal
    def restore(self) -> None:
        """Restore the console. This will be later moved into a proper deconstruction method."""
        if sys.stdout.isatty():
            curses.nocbreak()
            self.stdscr.keypad(0)
            curses.echo()
            curses.endwin()

    @check_for_terminal
    def update(self, match: Match) -> None:
        """Receive updates by observing the match object and prints them out formatted.

        Parameters
        ----------
        match : dict
            The observed match object.
        """
        self.stdscr.refresh()
        self.stdscr.clear()
        print(self.format_ascii(match))  # TODO: Refactor s.t. the output stream can be chosen by the user.

    def format_ascii(self, match: dict) -> None:
        """Format the provided match_data for the given battle_type.

        Parameters
        ----------
        match_data : dict
            dict containing match data generated by match.run().

        Returns
        -------
        str
            A formatted string on the basis of the match_data.
        """
        out = r'              _    _             _           _   _   _       ' + '\n\r' \
              + r'             / \  | | __ _  ___ | |__   __ _| |_| |_| | ___  ' + '\n\r' \
              + r'            / _ \ | |/ _` |/ _ \| |_ \ / _` | __| __| |/ _ \ ' + '\n\r' \
              + r'           / ___ \| | (_| | (_) | |_) | (_| | |_| |_| |  __/ ' + '\n\r' \
              + r'          /_/   \_\_|\__, |\___/|_.__/ \__,_|\__|\__|_|\___| ' + '\n\r' \
              + r'                      |___/                                  ' + '\n\r'

        out += '\nAlgobattle version {}\n\r'.format(version)

        return out + match.battle_wrapper.format_as_utf8(match.match_data)
