FROM mcr.microsoft.com/dotnet/sdk:7.0

WORKDIR /algobattle
COPY . ./
RUN dotnet publish -c Release -o /algobattle/out

WORKDIR /
CMD ["dotnet", "/algobattle/out/{{program.capitalize()}}.dll"]
